# Generated by Django 3.0.5 on 2020-04-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='course',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pname',
            new_name='ProjectName',
        ),
        migrations.AddField(
            model_name='project',
            name='grade',
            field=models.CharField(default=8, max_length=2),
            preserve_default=False,
        ),
    ]
