# Generated by Django 3.0.5 on 2020-04-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200421_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exams',
            new_name='Exam',
        ),
    ]
